name: Build image for production and push to docker hub

on: 
  push:
    branches:
      - master

jobs:
  build-and-deploy-frontend:
    name: Build and deploy frontend
    environment: Github Actions
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN}}